version: "3.2"
services:
  nginx:
    restart: "no"
    build: ./client/
    ports:
      - "80:80"
      - "443:443"
    links:
      - backend:backend
  backend:
    restart: "no"
    build: ./server/
    volumes:
      - ./db:/db
      - ./config:/config
      - ./log:/log
    command: >
      sh -c "node built/main.js"
