version: "3.2"
services:
  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
  nginx:
    restart: "no"
    build: ./client/
    ports:
      - "80:80"
    links:
      - backend:backend
  backend:
    restart: "no"
    build: ./server/
    volumes:
      - ./db:/db
      - ./config:/config
      - ./log:/log
