version: "3.2"
services:
  nginx:
    restart: "no"
    build: ./client/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    links:
      - backend:backend
  backend:
    restart: "no"
    build: ./server/
    volumes:
      - ./db:/app/db
      - ./feeds.yml:/feeds.yml
      - ./config.yaml:/config.yaml
    command: >
      sh -c "node built/main.js"
  
