version: "3.2"
services:
  redis:
    restart: always
    image: redis
    networks: 
      - app
  postgres:
    restart: always
    image: postgres
    networks: 
      - app
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ~/docker-data/pgdata:/var/lib/postgresql/data
  nginx:
    restart: always
    image: fwchen/oyster-client:latest
    ports:
      - "8070:80"
    networks: 
      - app
    links:
      - backend:backend
  backend:
    restart: "no"
    build: ./server/
    networks: 
      - app
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      VAPID_DETAIL_EMAIL: ${VAPID_DETAIL_EMAIL}
    volumes:
      - ./config:/config
      - ./log:/log
    depends_on:
      - postgres

networks:
  app:
