version: "3.2"
services:
  redis:
    restart: always
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./docker-data/redis:/data
    networks: 
      - oyster
  postgres:
    restart: always
    image: postgres:11.5
    networks:
      - oyster
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./docker-data/pgdata:/var/lib/postgresql/data
  web:
    restart: always
    image: fwchen/oyster-web:latest
    ports:
      - "8070:80"
    networks: 
      - oyster
    links:
      - server:server
  server:
    restart: always
    image: fwchen/oyster-server:latest
    networks: 
      - oyster
    volumes:
      - ./config:/config
      - ./log:/log
    depends_on:
      - postgres

networks:
  oyster:
