type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]

processors:
 - decode_json_fields:
     fields: ["message", "title", "sourceName", "type"]
     process_array: false
     max_depth: 1
     target: ""
     overwrite_keys: true
