SECRET_KEY: oyster # !IMPORTANT please replace this key
JWT_EXP: 2592000 # 30d
FEED_FILE_PATH: 'config/feeds.yml'

# redis
REDIS_HOST: "localhost"
REDIS_PORT: 6379

# postgres
POSTGRES_HOST: "localhost"
POSTGRES_USERNAME: "postgres"
POSTGRES_PASSWORD: "mysecretpassword"
POSTGRES_DB: "oyster"

VAPID_DETAIL_EMAIL: 'me@oyster'

# set proxy url
# proxy_url: "http://127.0.0.1:8888"